### PR TITLE
fix: prefetch shouldn't cancel

### PR DESCRIPTION
**Pull request by timdeschryver**

### CODE REVIEW

**Comment by SchlammSpringer** [comment]
@timdeschryver thxs for your support.
First everything seems fine, prefetch is working, 
but to make a showcase how our app is working, I put in 
`cache-devtool.component.ts`

`
<button (click)="refresh()">RefreshSome</button>
`

```
refresh(): void {
		refreshQuery('character-1');
		refreshQuery('character-2');
		refreshQuery('character-3');
		refreshQuery('character-4');
		refreshQuery('character-5');
	}
```

within `cache.ts` line 31 `tap(r => console.log(r.key)),`


when you load some characters and then click on 'RefreshSome' button, the cache is still broken.

**Comment by timdeschryver** [comment]
Thanks for the help @SchlammSpringer

**Comment by SchlammSpringer** [comment]
Great job, can´t see anymore problems. Handle events in queue is a much more elegant solution I had in mind. 
@mtt-artis is everything for you ok?

**Comment by mtt-artis** [comment]
it's ok for me.
many thanks !

**Comment by timdeschryver** [comment]
Sweet! Thanks again @SchlammSpringer and @mtt-artis
I'm merging this PR, and then doing some last tests.
You can expect a new release on Monday.

**Pull request merged**
