### PR TITLE
fix: test and avoid jest deprecation message

### PR DESCRIPTION
**Pull request by Quraian**
I forked the project and tried to run the tests, however it doesn't seem to finish:

```
 RUNS  rx-query/__tests__/query.test.ts

Test Suites: 1 skipped, 4 passed, 4 of 6 total
Tests:       1 skipped, 9 passed, 10 total
Snapshots:   0 total
Time:        413 s
```

After some debugging I found the test that was causing this issue. After increasing the timeout for the event the test passes.

Also, some change to avoid the following deprecation message:
```
ts-jest[root] (WARN) Import setup jest file via `import 'jest-preset-angular';` is deprecated and will be removed in v9.0.0. Please switch to `import 'jest-preset-angular/setup-jest';`
```

### CODE REVIEW

**Comment by timdeschryver** [comment]
Hmmmm, the build isn't that happy about it 😅

**Review by timdeschryver — COMMENTED** [review]
Hi @Quraian thanks for the PR, could you rebase please?
I made some changes to the CI in order to make the CI green.

**Comment by Quraian** [comment]
Hi @timdeschryver , I hope I did it correctly.

**Review by timdeschryver — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
